# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_test1(self):
    self.driver.get("https://www.google.ca/")
    self.driver.set_window_size(1470, 845)
    self.driver.find_element(By.ID, "APjFqb").send_keys("automation panda")
    self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dmenKe h3").click()
    self.driver.find_element(By.LINK_TEXT, "Testing").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".wp-block-heading:nth-child(2)").text == "What is Software Testing?"
  











